name: bangfeed
description: "Feed Formulation Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase - NOUVELLES versions
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  
  # Notifications - NOUVELLE version
  flutter_local_notifications: ^19.4.2
  
  # Charts
  fl_chart: ^0.66.2

  # Base de données locale
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # State management
  provider: ^6.1.2

  # Connectivité
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Hive code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true