name: bangfeed
description: "Feed Formulation Application"

publish_to: 'none'

version: 4.0.0+4

environment:
  # sdk: ^3.8.1
  sdk: '>=3.0.0 <4.0.0' # nouveau apres le soucis avec flutter


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase - NOUVELLES versions
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  
  # Notifications - NOUVELLE version
  flutter_local_notifications: ^19.4.2
  
  # Charts
  fl_chart: ^0.66.2

  # Base de données locale
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # State management
  provider: ^6.1.2

  # Connectivité
  # connectivity_plus: ^7.0.0
  connectivity_plus: ^6.0.3


  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.4.0
  http: ^1.5.0
  uuid: ^4.5.2
  url_launcher: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

  # Hive code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logoremovebg.png"
  remove_alpha_ios: true


flutter_native_splash:
  color: "#ffffff"
  image: images/logoremovebg.png
  android_12:  
    image: images/logoremovebg.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

  android: true
  ios: true
  web: true  
  fullscreen: true  


flutter:
  uses-material-design: true



  # Assets
  assets:
    - images/
    - images/logoremovebg.png
